#!/bin/sh

# xmonad startup script
#
# Based on content from
#     https://github.com/davidbrewer/xmonad-ubuntu-conf/blob/master/start-xmonad

export METASYSTEM_XMONAD_BIN=${METASYSTEM_XMONAD_BIN}

${METASYSTEM_XMONAD_BIN}/xmonad-setup &&\
exec xmonad


