# lib/bash/color.sh

export         NAKED_BLUE="\033[0;34m"
export   NAKED_LIGHT_BLUE="\033[1;34m"
export        NAKED_GREEN="\033[0;32m"
export  NAKED_LIGHT_GREEN="\033[1;32m"
export         NAKED_CYAN="\033[0;36m"
export   NAKED_LIGHT_CYAN="\033[1;36m"
export          NAKED_RED="\033[0;31m"
export    NAKED_LIGHT_RED="\033[1;31m"
export       NAKED_PURPLE="\033[0;35m"
export NAKED_LIGHT_PURPLE="\033[1;35m"
export       NAKED_YELLOW="\033[0;33m"
export NAKED_LIGHT_YELLOW="\033[1;33m"
export         NAKED_GRAY="\033[0;37m"
export        NAKED_WHITE="\033[1;37m"
export    NAKED_NO_COLOUR="\033[0m"
export     NAKED_NO_COLOR=$NAKED_NO_COLOUR

export         BLUE="\[${NAKED_BLUE}\]"
export   LIGHT_BLUE="\[${NAKED_LIGHT_BLUE}\]"
export        GREEN="\[${NAKED_GREEN}\]"
export  LIGHT_GREEN="\[${NAKED_LIGHT_GREEN}\]"
export         CYAN="\[${NAKED_CYAN}\]"
export   LIGHT_CYAN="\[${NAKED_LIGHT_CYAN}\]"
export          RED="\[${NAKED_RED}\]"
export    LIGHT_RED="\[${NAKED_LIGHT_RED}\]"
export       PURPLE="\[${NAKED_PURPLE}\]"
export LIGHT_PURPLE="\[${NAKED_LIGHT_PURPLE}\]"
export       YELLOW="\[${NAKED_YELLOW}\]"
export LIGHT_YELLOW="\[${NAKED_LIGHT_YELLOW}\]"
export         GRAY="\[${NAKED_GRAY}\]"
export        WHITE="\[${NAKED_WHITE}\]"
export    NO_COLOUR="\[${NAKED_NO_COLOUR}\]"
export     NO_COLOR=$NO_COLOUR

