# .bashrc

if [[ -z $METASYSTEM_ROOT ]]; then
	source ${METASYSTEM_ROOT}/home/profile
fi

if [[ -n $PS1 ]]; then
	source ~/.metasystem-config
	source ${METASYSTEM_ROOT}/home/shrc
	#metasystem_cd ~
fi

